pin arm64 for testing

diff --git a/.github/workflows/build-tool-packages.yml b/.github/workflows/build-tool-packages.yml
--- a/.github/workflows/build-tool-packages.yml
+++ b/.github/workflows/build-tool-packages.yml
@@ -16,6 +16,11 @@ on:
         description: "Tool version to build and upload"
         required: true
         type: string
+      architecture:
+        description: "Architecture of the tool"
+        required: false
+        type: string
+        default: 'arm64'
       publish-release:
         description: "Whether to publish releases"
         required: true
@@ -30,7 +35,7 @@ jobs:
     name: Build ${{ inputs.tool-name }} ${{ inputs.tool-version }} [${{ matrix.platform }}]
     runs-on: ubuntu-latest
     env: 
-      ARTIFACT_NAME: ${{ inputs.tool-name }}-${{ inputs.tool-version }}-${{ matrix.platform }}-x64
+      ARTIFACT_NAME: ${{ inputs.tool-name }}-${{ inputs.tool-version }}-${{ matrix.platform }}-${{ inputs.architecture }}
     strategy:
       fail-fast: false
       matrix:
@@ -43,7 +48,8 @@ jobs:
     - name: Build ${{ inputs.tool-name }} ${{ inputs.tool-version }}
       run: |
         ./builders/build-${{ inputs.tool-name }}.ps1 -Version ${{ inputs.tool-version }} `
-                                                     -Platform ${{ matrix.platform }}
+                                                     -Platform ${{ matrix.platform }} `
+                                                     -Architecture ${{ inputs.architecture }}
 
     - name: Publish artifact
       uses: actions/upload-artifact@v3
@@ -51,88 +57,91 @@ jobs:
         name: ${{ env.ARTIFACT_NAME }}
         path: ${{ runner.temp }}/artifact
 
-  test:
-    name: Test ${{ inputs.tool-name }} ${{ inputs.tool-version }} [${{ matrix.platform }}]
-    needs: build
-    runs-on: ${{ matrix.os }}
-    env: 
-      ARTIFACT_NAME: ${{ inputs.tool-name }}-${{ inputs.tool-version }}-${{ matrix.platform }}-x64
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-        - os: ubuntu-latest
-          platform: linux
-        - os: macos-latest
-          platform: darwin
-        - os: windows-latest
-          platform: win32
-    steps:
-    - uses: actions/checkout@v3
-      with:
-        submodules: true
+  # test:
+  #   name: Test ${{ inputs.tool-name }} ${{ inputs.tool-version }} [${{ matrix.platform }}]
+  #   needs: build
+  #   runs-on: ${{ matrix.os }}
+  #   env: 
+  #     ARTIFACT_NAME: ${{ inputs.tool-name }}-${{ inputs.tool-version }}-${{ matrix.platform }}-${{ inputs.architecture }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #       - os: ubuntu-latest
+  #         platform: linux
+  #       - os: macos-latest
+  #         platform: darwin
+  #       - os: windows-latest
+  #         platform: win32
+  #       # - os: macos-13_arm64
+  #       #   platform: darwin
+  #       #   architecture: arm64
+  #   steps:
+  #   - uses: actions/checkout@v3
+  #     with:
+  #       submodules: true
 
-    - name: Fully cleanup the toolcache directory before testing
-      run: ./helpers/clean-toolcache.ps1 -ToolName "${{ inputs.tool-name }}"
+  #   - name: Fully cleanup the toolcache directory before testing
+  #     run: ./helpers/clean-toolcache.ps1 -ToolName "${{ inputs.tool-name }}"
 
-    - name: Download artifact
-      uses: actions/download-artifact@v3
-      with:
-        path: ${{ runner.temp }}
+  #   - name: Download artifact
+  #     uses: actions/download-artifact@v3
+  #     with:
+  #       path: ${{ runner.temp }}
 
-    - name: Extract files
-      run: |
-        if ('${{ matrix.platform }}' -eq 'win32') {
-          if ('${{ inputs.tool-name }}' -eq 'node') {
-            $artifactName = "${{ env.ARTIFACT_NAME }}.7z"
-          } elseif ('${{ inputs.tool-name }}' -eq 'go') {            
-            $artifactName = "${{ env.ARTIFACT_NAME }}.zip"
-          } else {
-            Write-Host "Unsupported tool - ${{ inputs.tool-name }}"
-            exit 1
-          }
+  #   - name: Extract files
+  #     run: |
+  #       if ('${{ matrix.platform }}' -eq 'win32') {
+  #         if ('${{ inputs.tool-name }}' -eq 'node') {
+  #           $artifactName = "${{ env.ARTIFACT_NAME }}.7z"
+  #         } elseif ('${{ inputs.tool-name }}' -eq 'go') {            
+  #           $artifactName = "${{ env.ARTIFACT_NAME }}.zip"
+  #         } else {
+  #           Write-Host "Unsupported tool - ${{ inputs.tool-name }}"
+  #           exit 1
+  #         }
           
-          7z.exe x "$artifactName" -y | Out-Null 
-        } else {
-          $artifactName = "${{ env.ARTIFACT_NAME }}.tar.gz"
-          tar -xzf $artifactName
-        }
-      working-directory: ${{ runner.temp }}/${{ env.ARTIFACT_NAME }}
+  #         7z.exe x "$artifactName" -y | Out-Null 
+  #       } else {
+  #         $artifactName = "${{ env.ARTIFACT_NAME }}.tar.gz"
+  #         tar -xzf $artifactName
+  #       }
+  #     working-directory: ${{ runner.temp }}/${{ env.ARTIFACT_NAME }}
 
-    - name: Apply build artifact to the local machine
-      run: |
-        if ('${{ matrix.platform }}' -eq 'win32') { powershell ./setup.ps1 } else { sh ./setup.sh }
-      working-directory: ${{ runner.temp }}/${{ env.ARTIFACT_NAME }}
+  #   - name: Apply build artifact to the local machine
+  #     run: |
+  #       if ('${{ matrix.platform }}' -eq 'win32') { powershell ./setup.ps1 } else { sh ./setup.sh }
+  #     working-directory: ${{ runner.temp }}/${{ env.ARTIFACT_NAME }}
 
-    - name: Setup Node.js ${{ inputs.tool-version }}
-      if: inputs.tool-name == 'node'
-      uses: actions/setup-node@v3
-      with:
-        node-version: ${{ inputs.tool-version }}
+  #   - name: Setup Node.js ${{ inputs.tool-version }}
+  #     if: inputs.tool-name == 'node'
+  #     uses: actions/setup-node@v3
+  #     with:
+  #       node-version: ${{ inputs.tool-version }}
 
-    - name: Setup Go ${{ inputs.tool-version }}
-      if: inputs.tool-name == 'go'
-      uses: actions/setup-go@v3
-      with:
-        go-version: ${{ inputs.tool-version }}
+  #   - name: Setup Go ${{ inputs.tool-version }}
+  #     if: inputs.tool-name == 'go'
+  #     uses: actions/setup-go@v3
+  #     with:
+  #       go-version: ${{ inputs.tool-version }}
 
-    - name: Wait for the logs
-      run: |
-        Write-Host "Fake step that does nothing"
-        Write-Host "We need it because log from the previous step 'Setup ${{ inputs.tool-name }}' is not available here yet."
-        Write-Host "In testing step we analyze build log of 'Setup ${{ inputs.tool-name }}' task"
-        Write-Host "to determine if ${{ inputs.tool-name }} version was consumed from cache or if it was downloaded"
-        for ($i = 0; $i -lt 200; $i++) { Get-Random }
+  #   - name: Wait for the logs
+  #     run: |
+  #       Write-Host "Fake step that does nothing"
+  #       Write-Host "We need it because log from the previous step 'Setup ${{ inputs.tool-name }}' is not available here yet."
+  #       Write-Host "In testing step we analyze build log of 'Setup ${{ inputs.tool-name }}' task"
+  #       Write-Host "to determine if ${{ inputs.tool-name }} version was consumed from cache or if it was downloaded"
+  #       for ($i = 0; $i -lt 200; $i++) { Get-Random }
 
-    - name: Run tests
-      env: 
-        VERSION: ${{ inputs.tool-version }}
-      run: |
-        Install-Module Pester -Force -Scope CurrentUser
-        Import-Module Pester
-        $toolName = (Get-Culture).TextInfo.ToTitleCase("${{ inputs.tool-name }}")
-        Invoke-Pester -Script ./$toolName.Tests.ps1 -EnableExit
-      working-directory: ./tests
+  #   - name: Run tests
+  #     env: 
+  #       VERSION: ${{ inputs.tool-version }}
+  #     run: |
+  #       Install-Module Pester -Force -Scope CurrentUser
+  #       Import-Module Pester
+  #       $toolName = (Get-Culture).TextInfo.ToTitleCase("${{ inputs.tool-name }}")
+  #       Invoke-Pester -Script ./$toolName.Tests.ps1 -EnableExit
+  #     working-directory: ./tests
 
   publish_release:
     name: Publish release
